// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaProyectos.Database;

#nullable disable

namespace SistemaProyectos.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaProyectos.Model.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("ntext")
                        .HasColumnName("Name");

                    b.Property<double>("Progress")
                        .HasColumnType("float")
                        .HasColumnName("Progress");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("ntext")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SistemaProyectos.Model.JobMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("Hour")
                        .HasColumnType("datetime")
                        .HasColumnName("Hour");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("MaterialId");

                    b.ToTable("JobMaterials");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("ntext")
                        .HasColumnName("Name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("Name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("ntext")
                        .HasColumnName("State");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Job", b =>
                {
                    b.HasOne("SistemaProyectos.Model.Project", null)
                        .WithMany("Jobs")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("SistemaProyectos.Model.JobMaterial", b =>
                {
                    b.HasOne("SistemaProyectos.Model.Job", null)
                        .WithMany("JobMaterials")
                        .HasForeignKey("JobId");

                    b.HasOne("SistemaProyectos.Model.Material", null)
                        .WithMany("JobMaterials")
                        .HasForeignKey("MaterialId");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Job", b =>
                {
                    b.Navigation("JobMaterials");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Material", b =>
                {
                    b.Navigation("JobMaterials");
                });

            modelBuilder.Entity("SistemaProyectos.Model.Project", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
